version: '3.4'

services:

  game:
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=game
      - WORD_HOST=word:8080
      - DOCKER_USE=true
    ports:
      - "8080:8080"

  word:
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=word
    ports:
      - "8081:8080"

  player1:
    environment:
      - SERVER_PORT=9000
      - SERVER_HOST=player1
      - GAME_HOST=game:8080
      - WORD_HOST=word:8080
      - DOCKER_USE=true
    ports:
      - "9000:9000"

  player2:
    environment:
      - SERVER_PORT=9001
      - SERVER_HOST=player2
      - GAME_HOST=game:8080
      - WORD_HOST=word:8080
      - DOCKER_USE=true
    ports:
      - "9001:9001"

  player3:
    environment:
      - SERVER_PORT=9002
      - SERVER_HOST=player3
      - GAME_HOST=game:8080
      - WORD_HOST=word:8080
      - DOCKER_USE=true
    ports:
      - "9002:9002"

  player4:
    environment:
      - SERVER_PORT=9003
      - SERVER_HOST=player4
      - GAME_HOST=game:8080
      - WORD_HOST=word:8080
      - DOCKER_USE=true
    ports:
      - "9003:9003"